name: KumoCLI Deploy

run-name: ${{ github.actor }} has pushed changes to ${{ github.event.ref }}

on:
    push:
        branches:
            - main

    pull_request: 
      branches:
      - 'release/kumo/*'
      types: [opened,reopened,synchronize]

jobs:
  kumo_cli_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', 3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install -e .
    - name: Run tests
      run: |
        source venv/bin/activate
        cd kumo_instance_manager/tests
        pytest test_kumo.py
